use fly_emirates_flight;
SELECT DISTINCT CANCELLATION_REASON
FROM flights;

ALTER TABLE flights
ADD COLUMN CANCELLATION_REASON_DESC VARCHAR(50);
SET SQL_SAFE_UPDATES = 0;
UPDATE flights
SET CANCELLATION_REASON_DESC =
CASE
    WHEN CANCELLATION_REASON = 'A' THEN 'Airline/Carrier'
    WHEN CANCELLATION_REASON = 'B' THEN 'Weather'
    WHEN CANCELLATION_REASON = 'C' THEN 'National Air System'
    WHEN CANCELLATION_REASON = 'D' THEN 'Security'
    ELSE 'Not Cancelled'
END;
SELECT DISTINCT
CANCELLATION_REASON,
CANCELLATION_REASON_DESC
FROM flights;

